# Generated by Django 4.2.3 on 2023-07-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_gadgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=50)),
                ('g_price', models.IntegerField(max_length=50)),
                ('g_warranty', models.CharField(max_length=50)),
                ('g_image', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'table_gadgets',
            },
        ),
    ]
