# Generated by Django 4.2.3 on 2023-07-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0003_rename_g_image_table_gadgets_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_gadgets',
            name='g_category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
