# Generated by Django 4.2.3 on 2023-08-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0004_table_gadgets_g_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_gadgets',
            name='g_price',
            field=models.IntegerField(),
        ),
    ]
